services:
  db:
    image: postgres
    container_name: postgressql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: egilmore
      POSTGRES_PASSWORD: pg.ERGB.22
      POSTGRES_DB: aprendemas
    volumes:
      - ./postgressql_data:/var/lib/postgresql/data
      - ./aprendemas_back.sql:/docker-entrypoint-initdb.d/aprendemas_back.sql
